// Code generated by github.com/xhd2015/go-vendor-pack/cmd/go-pack. DO NOT EDIT.
package pack

var testPack = "H4sIAAAAAAAA/+zUv26DMBAGcNb4KTy2Q81nYqCv44LjIGEu9Z+Ix68SogyVkmahbST/lgPdSRzDd5aEo75YFQA0Sp1r2zTnimp5P5GqvT4DKCAr1NuCY921FilE7QvA6e7uXIh6t7vTvy5/qU/CUZ9Gw82s3WE0jFniUkjFmDefafCGv7CNHeI+fYiOXDnv+wqyLi29DVM4mC7yIwSEatnG0qgnK8jbci4j0RhOvXcB9sr++jezG5b8i6PxYaAprPKNH/Nff8//tq1y/n/FY9l+cOrmAbicF57vQJZl2X/xFQAA//9CYn40AAwA"
